#Override containers for dev
version: "2.4"
services:

  reverse_proxy:
    volumes:
      - .local/nginx:/data
    depends_on:
      - smtp

  ui:
    command: yarn start
    mem_limit: 1g
    stdin_open: true
    volumes:
      - ./ui:/app

  server:
    command: ["yarn", "debug"]
    ports:
      - "127.0.0.1:9229:9229" #Allows remote debugging
    volumes:
      - .local/server:/data
      - ./server/src:/app/src
    environment:
      - SIRIUS_ENV=dev
      - SIRIUS_SMTP_HOST=smtp
      - SIRIUS_SMTP_PORT=1025
    depends_on:
      - smtp

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - .local/mongodb:/data

  smtp:
    image: mailhog/mailhog
    container_name: sirius_smtp
    mem_limit: 128m
    ports:
      - 1025:1025
    networks:
      - sirius_network
    environment:
      - MH_UI_WEB_PATH=smtp
