#Override containers for dev
version: "2.4"
services:
  reverse_proxy:
    ports:
      - 80:80
    volumes:
      - .local/nginx:/data
    depends_on:
      - smtp

  ui:
    command: yarn start
    mem_limit: 1g
    stdin_open: true
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - ./ui:/app
    build:
      args:
        - SIRIUS_ENV=dev

  server:
    command: yarn dev
    networks:
      - sirius_network
    ports:
      - "127.0.0.1:9229:9229" #Allows remote debugging
    volumes:
      - .local/server:/data
      - ./server/src:/app/src
    environment:
      - SIRIUS_ENV=dev
      - SIRIUS_PUBLIC_URL=http://localhost
      - SIRIUS_SMTP_HOST=smtp
      - SIRIUS_SMTP_PORT=1025
    depends_on:
      - smtp

  postgres:
    image: postgres:15.5
    container_name: sirius_postgres
    restart: unless-stopped
    networks:
      - sirius_network
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - sirius_postgres_data:/var/lib/postgresql/data:z

  smtp:
    image: axllent/mailpit:v1.5.5
    container_name: sirius_smtp
    deploy:
      resources:
        limits:
          memory: 128m
      update_config:
        failure_action: rollback
      rollback_config:
        parallelism: 0
    networks:
      - sirius_network
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - sirius_mailpit_data:/data
    environment:
      - MP_DATA_FILE=/data/mailpit.db
      - MP_WEBROOT=smtp

volumes:
  sirius_mailpit_data:
    driver: local
    name: sirius_mailpit_data
  sirius_postgres_data:
    driver: local
    name: sirius_postgres_data
