services:
  postgres:
    image: postgres:15.5
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - sirius_postgres_data:/var/lib/postgresql/data:z
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d sirius'"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

  smtp:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      - MP_DATA_FILE=/data/mailpit.db
      - MP_WEBROOT=smtp
    volumes:
      - sirius_smtp_data:/data

volumes:
  sirius_postgres_data:
    driver: local
    name: sirius_postgres_data
  sirius_smtp_data:
    driver: local
    name: sirius_smtp_data
