- name: Création des répertoires tools
  file:
    path: "/opt/sirius/tools/{{ item.path }}/"
    state: directory
  with_filetree:
    - app/tools
  when: item.state == 'directory'

- name: Copie des fichiers 'overrides'
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/opt/sirius/tools/{{ item.path }}"
    mode: "g+x"
  with_filetree:
    - app/tools
  when: item.state == 'file'

- name: Copie des scripts bash
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/sirius/{{ item | basename }}
    mode: "g+x"
  with_fileglob:
    - "app/*.sh"

- name: Nettoyage des permissions sudo pour le groupe 'mna'
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "mna"

