version: "2.4"
services:
  ui:
    build:
      args:
        - SIRIUS_ENV=production

  server:
    environment:
      - SIRIUS_ENV=production
      - SIRIUS_LOG_LEVEL=info
      - SIRIUS_LOG_TYPE=json
      - SIRIUS_PUBLIC_URL=https://sirius.inserjeunes.beta.gouv.fr
      - SIRIUS_SMTP_HOST=smtp-relay.brevo.com
      - SIRIUS_SMTP_PORT=587
      - SIRIUS_SMTP_SECURE=true
      - SIRIUS_SLACK_WEBHOOK_URL={{ vault[env_type].SIRIUS_SLACK_WEBHOOK_URL }}
      - SIRIUS_SMTP_AUTH_USER=contact@inserjeunes.beta.gouv.fr
      - SIRIUS_SMTP_AUTH_PASS={{ vault[env_type].SIRIUS_SMTP_AUTH_PASS }}
      - SIRIUS_EMAIL_FROM=contact-sirius@inserjeunes.beta.gouv.fr
      - SIRIUS_AUTH_JWT_SECRET={{ vault[env_type].SIRIUS_AUTH_JWT_SECRET }}
      - SIRIUS_AUTH_REFRESH_TOKEN_SECRET={{ vault[env_type].SIRIUS_AUTH_REFRESH_TOKEN_SECRET }}
      - SIRIUS_AUTH_SESSION_EXPIRY=900
      - SIRIUS_AUTH_REFRESH_TOKEN_EXPIRY=2592000
      - SIRIUS_AUTH_COOKIE_SECRET={{ vault[env_type].SIRIUS_AUTH_COOKIE_SECRET }}
      - SIRIUS_SLACK_TOKEN={{ vault[env_type].SIRIUS_SLACK_TOKEN }}
      - SIRIUS_SLACK_SIGNING_SECRET={{ vault[env_type].SIRIUS_SLACK_SIGNING_SECRET }}
      - SIRIUS_SLACK_CHANNEL=sirius-bot
      - SIRIUS_SENTRY_DSN=https://e7c750d2c1c94092ba24d85896703a47@sentry.incubateur.net/152
      - SIRIUS_PSQL_URI={{ vault[env_type].SIRIUS_PSQL_URI }}
      - SIRIUS_PSQL_CA={{ vault[env_type].SIRIUS_PSQL_CA }}


