version: 2.1
orbs:
  docker: circleci/docker@1.0.1
  slack: circleci/slack@3.4.2
jobs:
  test:
    executor:
      name: docker/docker
    steps:
      - setup_remote_docker
      - docker/install-docker-tools
      - checkout
      - run:
          name: Run tests inside containers
          command: |
            docker-compose -f docker-compose.yml up -d --no-deps server mongodb
            docker exec sirius_server yarn test
      - slack/status:
          fail_only: true
          webhook: ${SLACK_WEBHOOK}

workflows:
  continuous-integration:
    jobs:
      - test
