#!/usr/bin/env bash
set -euo pipefail

# A hook script to verify that we don't commit files that could contain sensible data or credentials like json, csv, xls(x) or .env

readonly SENSIBLE_FILES_PATTERN="\.(csv|xls|xls(x?)|json|env)$"
readonly EXCEPTION="package.json$"
readonly SENSIBLE_FILES=$(git diff --cached --name-only | grep -v -E "$EXCEPTION" | grep -E "$SENSIBLE_FILES_PATTERN")

if [ -z "$SENSIBLE_FILES" ]; then
  exit 0
fi

echo
echo "ERROR: Preventing commit of potentially sensible files:"
echo
echo "${SENSIBLE_FILES}"
echo
echo "Either reset those files, add them to .gitignore or remove them."
echo
echo "If you know what you are doing, please double-check that you are not commiting"
echo "any credentials, password or sensible data and run git commit again with --no-verify."
echo
exit 1
