version: "2.4"
services:
  reverse_proxy:
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - /opt/sirius/data/nginx:/data
      - /opt/sirius/data/ssl:/ssl:ro
      - /opt/sirius/.overrides/reverse_proxy/sirius.conf:/etc/nginx/conf.d/sirius.conf:ro  

  ui:
    command: yarn serve

  server:
    volumes:
      - /opt/sirius/data/server:/data
