version: "2.4"
services:
  ui:
    build:
      args:
        - SIRIUS_ENV=recette

  server:
    environment:
      - SIRIUS_ENV=recette
      - SIRIUS_LOG_LEVEL=info
      - SIRIUS_LOG_TYPE=json
      - SIRIUS_MONGODB_URI={{ vault[env_type].SIRIUS_MONGODB_URI }}
      - SIRIUS_PUBLIC_URL=https://sirius-recette.inserjeunes.beta.gouv.fr
      - SIRIUS_SMTP_HOST=smtp
      - SIRIUS_SMTP_PORT=1025
      - SIRIUS_SMTP_SECURE=true
      - SIRIUS_SLACK_WEBHOOK_URL={{ vault[env_type].SIRIUS_SLACK_WEBHOOK_URL }}
      - SIRIUS_SMTP_AUTH_USER=contact@inserjeunes.beta.gouv.fr
      - SIRIUS_EMAIL_FROM=contact-sirius@inserjeunes.beta.gouv.fr
      - SIRIUS_AUTH_JWT_SECRET={{ vault[env_type].SIRIUS_AUTH_JWT_SECRET }}
      - SIRIUS_AUTH_REFRESH_TOKEN_SECRET={{ vault[env_type].SIRIUS_AUTH_REFRESH_TOKEN_SECRET }}
      - SIRIUS_AUTH_SESSION_EXPIRY=900
      - SIRIUS_AUTH_REFRESH_TOKEN_EXPIRY=2592000
      - SIRIUS_AUTH_COOKIE_SECRET={{ vault[env_type].SIRIUS_AUTH_COOKIE_SECRET }}
      - SIRIUS_SLACK_CHANNEL=sirius-bot
      - SIRIUS_SENTRY_DSN=https://e7c750d2c1c94092ba24d85896703a47@sentry.incubateur.net/152
      - SIRIUS_PSQL_URI={{ vault[env_type].SIRIUS_PSQL_URI }}
    depends_on:
      - smtp

  smtp:
    image: axllent/mailpit:v1.5.5
    container_name: sirius_smtp
    deploy:
      resources:
        limits:
          memory: 128m
      update_config:
        failure_action: rollback
      rollback_config:
        parallelism: 0
    networks:
      - sirius_network
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - sirius_mailpit_data:/data
    environment:
      - MP_DATA_FILE=/data/mailpit.db
      - MP_WEBROOT=smtp

  mongodb:
    image: mongo:4.4.1-bionic
    command: mongod --auth
    container_name: sirius_mongodb
    tty: true
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - sirius_network
    volumes:
      - /opt/sirius/data/mongodb/db:/data/db
      - /opt/sirius/data/mongodb/configdb:/data/configdb
      - /opt/sirius/data/mongodb/backups:/data/backups
      - /opt/sirius/.overrides/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  postgres:
    image: postgres:15.5
    container_name: sirius_postgres
    restart: unless-stopped
    networks:
      - sirius_network
    environment:
      - POSTGRES_PASSWORD={{ vault[env_type].SIRIUS_PSQL_PWD }}
    ports:
      - "5432:5432"
    volumes:
      - sirius_postgres_data:/var/lib/postgresql/data:z

volumes:
  sirius_mailpit_data:
    driver: local
    name: sirius_mailpit_data
  sirius_postgres_data:
    driver: local
    name: sirius_postgres_data