- name: "Clone du repository (branche : {{ git_revision }})"
  become: yes
  git:
    repo: "https://github.com/mission-apprentissage/sirius.git"
    version: "{{ git_revision }}"
    force: yes
    accept_hostkey: yes
    dest: /opt/sirius/repository

- name: Prune docker images
  become: yes
  community.docker.docker_prune:
    timeout: 300
    images: true
    images_filters:
      until: 12h

- name: Create and start services
  become: yes
  community.docker.docker_compose:
    project_src: /opt/sirius/repository
    build: true
    restarted: true
    files:
      - /opt/sirius/repository/docker-compose.yml
      - /opt/sirius/.overrides/docker-compose.common.yml
      - /opt/sirius/.overrides/docker-compose.env.yml
  vars:
    ansible_command_timeout: 3000
  register: output

- debug:
    var: output
