export interface RncpDetails {
  date_fin_validite_enregistrement: string | null;
  active_inactive: string | null;
  etat_fiche_rncp: string | null;
  niveau_europe: string | null;
  code_type_certif: string | null;
  type_certif: string | null;
  ancienne_fiche: string[] | null;
  nouvelle_fiche: string | null;
  demande: number;
  certificateurs:
    | {
        certificateur: string;
        siret_certificateur: string;
      }[]
    | null;
  nsf_code: string | null;
  nsf_libelle: string | null;
  romes: {
    rome: string;
    libelle: string;
  }[];
  blocs_competences: {
    numero_bloc: string;
    intitule: string;
    liste_competences: string;
    modalites_evaluation: string;
  }[];
  voix_acces: any;
  partenaires: {
    Nom_Partenaire: string;
    Siret_Partenaire: string;
    Habilitation_Partenaire: string;
  }[];
  rncp_outdated: boolean;
}

export type CatalogueFormation = {
  _id: string;
  cle_ministere_educatif: string | null;
  cfd: string | null;
  cfd_specialite: string | null;
  cfd_outdated: boolean;
  cfd_date_fermeture: string | null;
  cfd_entree: string | null;
  nom_academie: string | null;
  num_academie: string;
  code_postal: string;
  code_commune_insee: string | null;
  num_departement: string;
  nom_departement: string | null;
  region: string;
  localite: string;
  nom: string | null;
  intitule_long: string | null;
  intitule_court: string | null;
  diplome: string;
  niveau: string | null;
  onisep_url: string | null;
  onisep_intitule: string | null;
  onisep_libelle_poursuite: string | null;
  onisep_lien_site_onisepfr: string | null;
  onisep_discipline: string | null;
  onisep_domaine_sousdomaine: string;
  rncp_code: string | null;
  rncp_intitule: string | null;
  rncp_eligible_apprentissage: boolean;
  rncp_details: RncpDetails;
  rome_codes: string[];
  periode: string[];
  capacite: number | null;
  duree: number;
  annee: string | null;
  email: string | null;
  published: boolean;
  lieu_formation_adresse: string | null;
  lieu_formation_adresse_computed: string | null;
  lieu_formation_siret: string | null;
  id_rco_formation: string | null;
  id_formation: string | null;
  id_action: string | null;
  ids_action: string[];
  id_certifinfo: string | null;
  tags: string[];
  libelle_court: string | null;
  niveau_formation_diplome: string | null;
  bcn_mefs_10: {
    mef10: string;
    modalite?: {
      annee: string;
      duree: string;
    };
  }[];
  distance_lieu_formation_etablissement_formateur: number | null;
  niveau_entree_obligatoire: number | null;
  entierement_a_distance: boolean;
  etablissement_gestionnaire_id: string | null;
  etablissement_gestionnaire_siret: string;
  etablissement_gestionnaire_enseigne: string | null;
  etablissement_gestionnaire_uai: string | null;
  etablissement_gestionnaire_published: boolean;
  etablissement_gestionnaire_adresse: string | null;
  etablissement_gestionnaire_code_postal: string | null;
  etablissement_gestionnaire_code_commune_insee: string | null;
  etablissement_gestionnaire_localite: string | null;
  etablissement_gestionnaire_complement_adresse: string | null;
  etablissement_gestionnaire_cedex: string | null;
  etablissement_gestionnaire_entreprise_raison_sociale: string | null;
  etablissement_gestionnaire_region: string | null;
  etablissement_gestionnaire_num_departement: string | null;
  etablissement_gestionnaire_nom_departement: string | null;
  etablissement_gestionnaire_nom_academie: string | null;
  etablissement_gestionnaire_num_academie: string | null;
  etablissement_gestionnaire_siren: string | null;
  etablissement_gestionnaire_nda: string | null;
  etablissement_gestionnaire_date_creation: string | null;
  etablissement_gestionnaire_courriel: string | null;
  etablissement_formateur_id: string | null;
  etablissement_formateur_siret: string;
  etablissement_formateur_enseigne: string | null;
  etablissement_formateur_uai: string | null;
  etablissement_formateur_published: boolean;
  etablissement_formateur_adresse: string | null;
  etablissement_formateur_code_postal: string | null;
  etablissement_formateur_code_commune_insee: string | null;
  etablissement_formateur_localite: string;
  etablissement_formateur_complement_adresse: string | null;
  etablissement_formateur_cedex: string | null;
  etablissement_formateur_entreprise_raison_sociale: string | null;
  etablissement_formateur_region: string | null;
  etablissement_formateur_num_departement: string | null;
  etablissement_formateur_nom_departement: string | null;
  etablissement_formateur_nom_academie: string | null;
  etablissement_formateur_num_academie: string | null;
  etablissement_formateur_siren: string | null;
  etablissement_formateur_nda: string | null;
  etablissement_formateur_date_creation: string | null;
  etablissement_formateur_courriel: string | null;
  etablissement_reference: string | null;
  etablissement_reference_published: boolean;
  etablissement_reference_date_creation: string | null;
  created_at: string;
  last_update_at: string;
  geo_coordonnees_etablissement_formateur: string | null;
  geo_coordonnees_etablissement_gestionnaire: string | null;
  lieu_formation_geo_coordonnees: string | null;
  idea_geo_coordonnees_etablissement: string | null;
  distance: number | null;
  france_competence_infos: any | null;
  lieu_formation_geo_coordonnees_computed: string | null;
  intitule_rco: string | null;
  annee_incoherente: boolean;
  duree_incoherente: boolean;
  catalogue_published: boolean;
  etablissement_gestionnaire_certifie_qualite: boolean;
  etablissement_formateur_certifie_qualite: boolean;
  etablissement_reference_certifie_qualite: boolean;
  etablissement_gestionnaire_habilite_rncp: string | null;
  etablissement_formateur_habilite_rncp: string | null;
  etablissement_reference_habilite_rncp: string | null;
  forced_published: boolean;
  date_debut: string[];
  date_fin: string[];
  id_RCO: string | null;
  modalites_entrees_sorties: boolean[];
  contenu: string | null;
  objectif: string | null;
  code_formacode: string[];
  libelle_formacode: string | null;
  etablissement_formateur_actif: string | null;
  etablissement_gestionnaire_actif: string | null;
  num_tel: string | null;
  siret_actif: string | null;
  cle_me_remplace: string | null;
  cle_me_remplace_par: string | null;
  etablissement_lieu_formation_siret: string | null;
  etablissement_lieu_formation_uai: string | null;
  etablissement_lieu_siret_actif: string | null;
  id: string;
  createdBy: string;
};
