name: CI
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2.6

      - run: yarn --cwd server install
      - run: yarn --cwd server test

      - name: Send slack notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  deploy:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo '::set-env name=SIRIUS_HEAD_REF::${{ github.head_ref }}'

      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branchName::${SIRIUS_HEAD_REF:-${GITHUB_REF##*/}}"
        id: vars

      - shell: bash
        run: echo "${{steps.vars.outputs.branchName}}"

      - name: Checkout project
        uses: actions/checkout@v2
        if: github.ref == 'refs/heads/develop'

      - name: Request deployment
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: mission-apprentissage/sirius-infra
          token: ${{ secrets.DEVOPS_ACCESS_TOKEN }}
          event-type: deploy
          client-payload: '{"envName": "recette", "branchName":"${{ steps.vars.outputs.branchName }}"}'
        if: github.ref == 'refs/heads/develop'
